auth_modules:
  default:
    datasource:
      host: ${SERVER_IP:-localhost}
      port: ${POSTGRESQL0_PORT:-5433}
      database: ${PG_DATABASE:-postgres}
      user: ${POSTGRES_USER:-postgres}
      password: ${POSTGRES_PASSWORD:-postgres}
      ssl_mode: ${PG_SSL_MODE:-disable}
    metrics:
      - query: "SELECT COUNT(*) as count, 'user' as type FROM pg_user"
        metrics:
          - count:
              usage: "GAUGE"
              description: "Number of users"
          - type:
              usage: "LABEL"
              description: "Type of count"
      - query: "SELECT datname, pg_database_size(datname) as size FROM pg_database"
        metrics:
          - datname:
              usage: "LABEL"
              description: "Database name"
          - size:
              usage: "GAUGE"
              description: "Database size in bytes"
      - query: "SELECT state, count(*) as count FROM pg_stat_activity GROUP BY state"
        metrics:
          - state:
              usage: "LABEL"
              description: "Connection state"
          - count:
              usage: "GAUGE"
              description: "Number of connections in this state"
